### ISSUE TITLE
Page Error

### ISSUE THREAD

**Issue by TheBugYouCantFix** [goldsmith/Wikipedia#246] opened 2020-09-27 07:30 UTC
How do I catch PageError exception? It doesn't let me do that
I really need help.
Thanks

**Comment by alphapapa** [comment] 2020-10-20 02:59
This issue is not a bug report nor a feature request.  Support requests should be posted in the appropriate place, e.g. StackOverflow.  Please close this issue.

**Comment by TheBugYouCantFix** [comment] 2021-01-05 16:33
c

**Closed** 2021-01-05 16:33 UTC
